#!/bin/sh

rm -f /etc/config/simetbox_hash_configured /etc/config/hash 2>/dev/null

rm -f /etc/config/simet_installed/*_installed 2>/dev/null
rmdir /etc/config/simet_installed 2>/dev/null || :

if [ -f /etc/simet/simet1.conf ] ; then
	rm -f /etc/config/simet.conf
else
	mv -f /etc/config/simet.conf /etc/simet/simet1.conf
fi

if [ -f /etc/simet/tr069_server ] ; then
	rm -f /etc/config/tr069_server
else
	mv -f /etc/config/tr069_server /etc/simet/tr069_server
fi
exit 0
