#!/bin/sh

. /lib/functions.sh

valued_changed=0
field_removed=0

write_new_default_values()
{
	mkdir -p /tmp/config
	rm -f /tmp/config/simet_cron
	touch /tmp/config/simet_cron

	if [ -f /usr/lib/simet/simet_installed/simetbox_contentprovider_installed ] ; then
		uci -c /tmp/config set simet_cron.content_provider=content_provider
		uci -c /tmp/config set simet_cron.content_provider.time_step=60
		uci -c /tmp/config set simet_cron.content_provider.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_dns_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_dns=simet_dns
		uci -c /tmp/config set simet_cron.simet_dns.time_step=240
		uci -c /tmp/config set simet_cron.simet_dns.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_ntpd_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_ntpq=simet_ntpq
		uci -c /tmp/config set simet_cron.simet_ntpq.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_top10alexa_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_alexa=simet_alexa
		uci -c /tmp/config set simet_cron.simet_alexa.time_step=360
		uci -c /tmp/config set simet_cron.simet_alexa.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_bcp38_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_bcp38=simet_bcp38
		uci -c /tmp/config set simet_cron.simet_bcp38.time_step=720
		uci -c /tmp/config set simet_cron.simet_bcp38.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_ping_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_ping=simet_ping
		uci -c /tmp/config set simet_cron.simet_ping.time_step=60
		uci -c /tmp/config set simet_cron.simet_ping.W=11
		uci -c /tmp/config set simet_cron.simet_ping.c=3
		uci -c /tmp/config set simet_cron.simet_ping.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_base_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_test=simet_test
		uci -c /tmp/config set simet_cron.simet_test.time_step=180
		uci -c /tmp/config set simet_cron.simet_test.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_port25_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_port25=simet_port25
		uci -c /tmp/config set simet_cron.simet_port25.time_step=360
		uci -c /tmp/config set simet_cron.simet_port25.enable=true
	fi

	if [ -f /usr/lib/simet/simet_installed/simetbox_iftraffic_installed ] ; then
		uci -c /tmp/config set simet_cron.simet_send_if_traffic=simet_send_if_traffic
		uci -c /tmp/config set simet_cron.simet_send_if_traffic.time_step=20
		uci -c /tmp/config set simet_cron.simet_send_if_traffic.enable=true
	fi

	### SIMET Legado - removidos
	uci -c /tmp/config delete simet_cron.service_down || true
	uci -c /tmp/config delete simet_cron.auto_upgrade || true

	### SIMET MA - remove due to lmapd switch
	uci -c /tmp/config delete simet_cron.simet_measure || true

	uci -c /tmp/config commit simet_cron
}

option_cb() {
	local name="$1"
	local value="$2"

	local new_default_value="$(uci -c /tmp/config get simet_cron.$CONFIG_SECTION.$name 2>&1)"

	if [ "$new_default_value" != "uci: Entry not found" -a ! "$new_default_value" = "$value" ];
	then
		uci -c /tmp/config set simet_cron.$CONFIG_SECTION.$name=$value
		uci -c /tmp/config commit simet_cron
		valued_changed=1
		elif [ "$new_default_value" = "uci: Entry not found" ]; then
			field_removed=1
		fi
}

file_exists=1

if [ ! -f "/etc/config/simet_cron" ];
then
	touch /etc/config/simet_cron
	file_exists=0
fi

$(write_new_default_values)

config_load simet_cron

mv /tmp/config/simet_cron /etc/config/simet_cron

lua -e "require('simet.crontab_writer');generate_crontab()"

exit 0

