#!/bin/sh /etc/rc.common
# Copyright (C) 2017 NIC.br

START=50

openwrt_read_invariant_seed()
(
  # This is a hack, it is not perfect, and not that secure.
  # note: this can be quite expensive in CPU and wall time
  P=$( sed -En -e '/^mtd[0-9]/! d' -e '/rootfs|firmware|kernel/ d' -e 's#(mtd[^:]+).*#/dev/\1ro# ; p' < /proc/mtd ) || P=/dev/null
  [ -z "$P" ] && P=/dev/null
  SBXSEED=$( set -o pipefail ; { echo "NIC IV nhZ6wZivEdaW3+9kUXhpLSeWiOmOX12TK/ZO2pFmtdF8w" ; cat -- $P ; } | md5sum - | tr -dc 0-9a-zA-Z ) || return 1
  [ -z "$SBXSEED" ] && return 1
  printf "%s" "$SBXSEED"
  :
)

start() {
	if [ ! -f "/etc/config/hash" ]
	then
	  hash_mac_address=$(openwrt_read_invariant_seed 2>/dev/null) \
	    || hash_mac_address=$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | md5sum - | tr -dc 0-9a-zA-Z)
	  [ -n "$hash_mac_address" ] && echo "$hash_mac_address" > /etc/config/hash
	fi

	# load in the release data
	. /etc/openwrt_release

	prefix=""
	if test -n "${DISTRIB_ID}" && test "${DISTRIB_ID}" != "${DISTRIB_ID#SIMETBOX}" ; then
        	prefix="SIMETBOX-"
	fi

	if [ -f "/etc/config/simet_installed/simetbox_network_and_config_installed" ]
	then
		uci set easycwmp.@acs[0].periodic_interval='30'
		uci set easycwmp.@acs[0].username=$(get_mac_address.sh)
		uci set easycwmp.@acs[0].password=$(get_mac_address.sh)
		uci set easycwmp.@local[0].username=$(get_mac_address.sh)
		uci set easycwmp.@local[0].password=$(get_mac_address.sh)
		uci set easycwmp.@device[0].oui='SIMETBOX'
		uci set easycwmp.@acs[0].url=$(cat /etc/config/tr069_server)
		uci set easycwmp.@device[0].serial_number=$(get_mac_address.sh)
		device_procuct=$(grep -v "DEVICE_MANUFACTURER" /etc/device_info | grep -v "DEVICE_PRODUCT")
		echo "DEVICE_MANUFACTURER='$(grep -e "^machine" /proc/cpuinfo | awk '{print $3}')'
DEVICE_PRODUCT='$prefix$(/usr/bin/get_model.sh)'
$device_procuct" > /etc/device_info
		uci commit easycwmp

		acs_server=$(cat /etc/config/tr069_server | sed -e "s/http:\/\///g" | sed -e "s/https:\/\///g" | sed -e "s/\/.*//")
		ip_acs_server=$(ping -4 $acs_server -c 1 2>/dev/null | grep "64 bytes" | awk {'print $4'} | sed -e 's/://g')
		if [ "ip_acs_server" != "" ] ; then
			firewall=$(grep "Allow-TR-069" /etc/config/firewall)
			if [ "$firewall" == "" ] ; then
				echo "
config rule
        option name             Allow-TR-069
        option src              wan
        option src_ip           '$ip_acs_server'
        option proto            tcp
        option dest_port        7547
        option target           ACCEPT
        option family           ipv4
" >> /etc/config/firewall
				/etc/init.d/firewall restart
			else
				# fix proto='TCP' where it should have been proto='tcp'
				uci show firewall | sed -nE "/proto='TCP'/ { s/proto='TCP'/proto=tcp/ ; s/^/set / ; p }" \
					| uci batch && uci commit firewall
			fi
		fi
	fi


        mac_address=`/usr/bin/get_mac_address.sh`
	if [ -f /rom/etc/zabbix_agentd.conf ] ; then
		zabbix=$(zabbix_agentd -V | grep -e "v2\.")
		if [ "$zabbix" == "" ] ; then
			sed -e "s/<CHANGE_HOSTNAME>/$mac_address/" /rom/etc/zabbix_agentd_v3_simetbox.conf > /etc/zabbix_agentd.conf
		fi
		if [ "$zabbix" != "" ] ; then
			sed -e "s/<CHANGE_HOSTNAME>/$mac_address/" /rom/etc/zabbix_agentd_v2_simetbox.conf > /etc/zabbix_agentd.conf
		fi
	fi
	if [ -f /rom/etc/ntp.conf_simetbox ] ; then
		cp /etc/ntp.conf_simetbox /etc/ntp.conf
	fi
	/usr/bin/simetbox_register.sh 1>/dev/null 2>/dev/null&
}

